# Generated by Django 5.2.1 on 2025-10-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_alter_veiculo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
