# Generated by Django 5.2.1 on 2025-10-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_ordemservico_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='alinhamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alinhamento e Balanceamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='bateria',
            field=models.CharField(blank=True, choices=[('BOM', 'Bom'), ('REVISAR', 'Revisar/Trocar'), ('RUIM', 'Ruim')], max_length=20, null=True, verbose_name='Bateria'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_farol_alto_dir',
            field=models.BooleanField(default=False, verbose_name='Farol Alto Dir.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_farol_alto_esq',
            field=models.BooleanField(default=False, verbose_name='Farol Alto Esq.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_farol_baixo_dir',
            field=models.BooleanField(default=False, verbose_name='Farol Baixo Dir.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_farol_baixo_esq',
            field=models.BooleanField(default=False, verbose_name='Farol Baixo Esq.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_freio_dir',
            field=models.BooleanField(default=False, verbose_name='Freio Dir.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_freio_esq',
            field=models.BooleanField(default=False, verbose_name='Freio Esq.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_re_dir',
            field=models.BooleanField(default=False, verbose_name='Ré Dir.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_re_esq',
            field=models.BooleanField(default=False, verbose_name='Ré Esq.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_seta_dianteira_dir',
            field=models.BooleanField(default=False, verbose_name='Seta Diant. Dir.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_seta_dianteira_esq',
            field=models.BooleanField(default=False, verbose_name='Seta Diant. Esq.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_seta_traseira_dir',
            field=models.BooleanField(default=False, verbose_name='Seta Tras. Dir.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='luz_seta_traseira_esq',
            field=models.BooleanField(default=False, verbose_name='Seta Tras. Esq.'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='nivel_combustivel',
            field=models.CharField(blank=True, choices=[('VAZIO', 'Vazio'), ('RESERVA', 'Reserva'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('CHEIO', 'Cheio')], max_length=10, null=True, verbose_name='Nível de Combustível'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='observacoes_avarias',
            field=models.TextField(blank=True, null=True, verbose_name='Observações de Avarias (riscos, amassados, etc.)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='oleo_motor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Óleo do Motor'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='palheta_dianteira',
            field=models.CharField(blank=True, choices=[('BOM', 'Bom'), ('REVISAR', 'Revisar/Trocar'), ('RUIM', 'Ruim')], max_length=20, null=True, verbose_name='Palhetas Dianteiras'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='palheta_traseira',
            field=models.CharField(blank=True, choices=[('BOM', 'Bom'), ('REVISAR', 'Revisar/Trocar'), ('RUIM', 'Ruim')], max_length=20, null=True, verbose_name='Palhetas Traseiras'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='quilometragem',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quilometragem (km)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(verbose_name='Descrição Geral do Serviço'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='finalizada',
            field=models.BooleanField(default=False, verbose_name='Finalizada?'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total (R$)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='cadastros.veiculo', verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peca',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
