# Generated by Django 5.2.1 on 2025-10-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_ordemservico_alinhamento_ordemservico_bateria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pecas/'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='finalizada',
            field=models.BooleanField(default=False, verbose_name='Finalizada'),
        ),
    ]
