# Generated by Django 5.2.1 on 2025-10-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_cliente_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_abertura',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Serviço'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='finalizada',
            field=models.BooleanField(default=False, verbose_name='Finalizada'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='cadastros.veiculo'),
        ),
        migrations.CreateModel(
            name='ItemOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico_descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastros.ordemservico')),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.peca')),
            ],
        ),
    ]
