# Generated by Django 5.2.1 on 2025-10-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_ordemservico_alinhamento_ordemservico_bateria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AddField(
            model_name='peca',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pecas/'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='finalizada',
            field=models.BooleanField(default=False, verbose_name='Finalizada'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Peça'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='quantidade',
            field=models.PositiveIntegerField(help_text='Quantidade atual em estoque.'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='quantidade_minima',
            field=models.PositiveIntegerField(help_text='Quantidade mínima para acionar o alerta de estoque baixo.', verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (R$)'),
        ),
    ]
