# Generated by Django 5.2.1 on 2025-10-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_peca_options_peca_imagem_and_more'),
        ('cadastros', '0004_peca_imagem_alter_ordemservico_finalizada'),
    ]

    operations = [
    ]
