# Generated by Django 5.2.6 on 2025-10-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_ordemservico_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='itemordemservico',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='peca',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
