# Generated by Django 5.2.1 on 2025-10-08 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_merge_20251008_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.PositiveIntegerField()),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_utilizadas', to='cadastros.ordemservico')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.peca')),
            ],
            options={
                'verbose_name': 'Peça Utilizada',
                'verbose_name_plural': 'Peças Utilizadas',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
