# Generated by Django 5.2.1 on 2025-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_pecautilizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Nome Padrão da Empresa', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Logo da empresa.', null=True, upload_to='configuracoes/')),
                ('imagem_fundo', models.ImageField(blank=True, help_text='Imagem de fundo do sistema.', null=True, upload_to='configuracoes/')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato da empresa.', max_length=25, null=True)),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo da empresa.', null=True)),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
    ]
