# Generated by Django 5.2.1 on 2025-10-08 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_configuracoesgerais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoesgerais',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da empresa (usado na barra lateral e ícone da aba).', null=True, upload_to='configuracoes/'),
        ),
        migrations.AlterField(
            model_name='configuracoesgerais',
            name='nome_empresa',
            field=models.CharField(default='Centro Automotivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='pecautilizada',
            name='peca',
            field=models.ForeignKey(help_text='Peça do estoque a ser utilizada.', on_delete=django.db.models.deletion.PROTECT, to='cadastros.peca'),
        ),
        migrations.AlterField(
            model_name='pecautilizada',
            name='quantidade_utilizada',
            field=models.PositiveIntegerField(help_text='Quantidade da peça utilizada no serviço.'),
        ),
        migrations.AlterUniqueTogether(
            name='pecautilizada',
            unique_together={('ordem_servico', 'peca')},
        ),
    ]
