# Generated by Django 5.2.1 on 2025-10-15 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_configuracoesgerais_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAÇÃO', 'Criação'), ('ATUALIZAÇÃO', 'Atualização'), ('EXCLUSÃO', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('detalhes', models.TextField(help_text='Descrição detalhada da ação realizada.')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
