# Generated by Django

from django.db import migrations

def criar_permissao_dashboard(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    # A permissão é ancorada ao modelo User do app 'auth'
    user_content_type = ContentType.objects.get(
        app_label='auth',
        model='user'
    )

    # Cria a permissão se ela não existir
    Permission.objects.get_or_create(
        codename='view_dashboard',
        name='Pode visualizar o dashboard',
        content_type=user_content_type,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_cliente_options_alter_itemordemservico_options_and_more'),
    ]

    operations = [
        migrations.RunPython(criar_permissao_dashboard),
    ]