# Generated by Django 5.2.1 on 2025-10-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
