# Generated by Django 5.2.1 on 2025-10-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_peca_codigo_peca_aplicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='codigo',
            field=models.CharField(help_text='Código único para identificação da peça.', max_length=50, unique=True, verbose_name='Código da Peça'),
        ),
    ]
