# Generated by Django 5.2.1 on 2025-10-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alter_peca_codigo'),
    ]

    operations = [
    ]
