# Generated by Django 5.2.1 on 2025-10-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_populate_codigo_peca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='aplicacao',
            field=models.CharField(blank=True, help_text='Veículos ou aplicações compatíveis com a peça.', max_length=200, null=True, verbose_name='Aplicação/Carro'),
        ),
    ]
