# Generated by Django 5.2.1 on 2025-10-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_peca_aplicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='codigo',
        ),
    ]
