# Generated by Django 5.2.1 on 2025-10-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_cliente_cidade_cliente_estado_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='alinhamento',
            field=models.CharField(blank=True, choices=[('BOM', 'Bom'), ('REVISAR', 'Revisar/Trocar'), ('RUIM', 'Ruim')], max_length=50, null=True, verbose_name='Alinhamento e Balanceamento'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='oleo_motor',
            field=models.CharField(blank=True, choices=[('BOM', 'Bom'), ('REVISAR', 'Revisar/Trocar'), ('RUIM', 'Ruim')], max_length=50, null=True, verbose_name='Óleo do Motor'),
        ),
    ]
