# Generated by Django 5.2.1 on 2025-10-20 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_alter_ordemservico_alinhamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_os/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='cadastros.ordemservico')),
            ],
            options={
                'verbose_name': 'Anexo da Ordem de Serviço',
                'verbose_name_plural': 'Anexos das Ordens de Serviço',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ServicoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição do serviço ou custo adicional.', max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade do serviço.')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitário do serviço (opcional).', max_digits=10, null=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor total do serviço (calculado automaticamente se quantidade e valor_unitario forem informados).', max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_utilizados', to='cadastros.ordemservico')),
            ],
            options={
                'verbose_name': 'Serviço Utilizado',
                'verbose_name_plural': 'Serviços Utilizados',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
