# Generated by Django 5.2.1 on 2025-10-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_anexoordemservico_servicoutilizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={},
        ),
    ]
