# Generated by Django 5.2.1 on 2025-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_alter_ordemservico_options_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoesgerais',
            name='cor_primaria',
            field=models.CharField(default='#0d6efd', help_text='Cor principal do sistema (botões, links, sidebar ativa).', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracoesgerais',
            name='cor_secundaria',
            field=models.CharField(default='#10B981', help_text='Cor secundária/destaque (gradientes, hover da sidebar).', max_length=7),
        ),
    ]
