# Generated by Django 5.2.1 on 2025-10-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_configuracoesgerais_cor_primaria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
    ]
