# Generated by Django 5.2.1 on 2025-10-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_alter_peca_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
    ]
