# Generated by Django 5.2.1 on 2025-10-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_alter_peca_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='status_aprovacao',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('FINALIZADO', 'Finalizado')], default='AGUARDANDO', max_length=20, verbose_name='Status de Aprovação'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='observacoes_avarias',
            field=models.TextField(blank=True, null=True, verbose_name='Observações de Avarias e Finalização (riscos, amassados, etc.)'),
        ),
    ]
