# Generated by Django 5.2.1 on 2025-10-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_ordemservico_status_aprovacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='alerta_email_enviado',
            field=models.BooleanField(default=False, verbose_name='Alerta de Estoque Baixo Enviado'),
        ),
    ]
