# Generated by Django 5.2.1 on 2025-11-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracoesgerais',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'permissions': [('view_dashboard', 'Pode visualizar o dashboard')], 'verbose_name': 'Configuração Geral', 'verbose_name_plural': 'Configurações Gerais'},
        ),
    ]
