# Generated by Django 5.2.1 on 2025-11-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_alter_configuracoesgerais_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexoordemservico',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Anexo da Ordem de Serviço', 'verbose_name_plural': 'Anexos das Ordens de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='configuracoesgerais',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'permissions': [('view_dashboard', 'Pode visualizar o dashboard')], 'verbose_name': 'Configuração Geral', 'verbose_name_plural': 'Configurações Gerais'},
        ),
        migrations.AlterModelOptions(
            name='itemordemservico',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='peca',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AlterModelOptions(
            name='pecautilizada',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Peça Utilizada', 'verbose_name_plural': 'Peças Utilizadas'},
        ),
        migrations.AlterModelOptions(
            name='servicoutilizado',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Serviço Utilizado', 'verbose_name_plural': 'Serviços Utilizados'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
    ]
