# Generated by Django 5.2.1 on 2025-11-10 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_alter_anexoordemservico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='O caminho da página que o usuário tentou acessar (ex: /relatorios/vendas/)', max_length=255, verbose_name='Caminho da URL (Path)')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('negado', 'Negado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_analisadas', to=settings.AUTH_USER_MODEL, verbose_name='Analisado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Solicitação de Acesso',
                'verbose_name_plural': 'Solicitações de Acesso',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
