# Generated by Django 5.2.1 on 2025-11-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0030_solicitacaoacesso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitacaoAcesso',
        ),
    ]
