# Generated by Django 5.2.1 on 2025-11-12 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_delete_solicitacaoacesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_abertura',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
