# Generated by Django 5.2.1 on 2026-05-02 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Centro Estética Automotiva', max_length=100)),
                ('telefone_whatsapp', models.CharField(help_text='Telefone com DDD para WhatsApp', max_length=16)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracoes/', verbose_name='Logo')),
                ('imagem_fundo', models.ImageField(blank=True, null=True, upload_to='configuracoes/', verbose_name='Imagem de Fundo')),
                ('cor_fundo', models.CharField(default='#000000', max_length=7, verbose_name='Cor de Fundo')),
                ('cor_primaria', models.CharField(default='#00BFFF', max_length=7, verbose_name='Cor Primária (Azul Água)')),
                ('cor_contraste', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor de Contraste')),
                ('mensagem_whatsapp', models.TextField(default='Quero agendar {servico} para {data} às {horario}', help_text='Use {servico}, {data}, {horario}, {nome} como variáveis', verbose_name='Mensagem do WhatsApp')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='DiaBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data Bloqueada')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Dia Bloqueado',
                'verbose_name_plural': 'Dias Bloqueados',
            },
        ),
        migrations.CreateModel(
            name='FotoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_trabalho/', verbose_name='Imagem')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto do Trabalho',
                'verbose_name_plural': 'Fotos dos Trabalhos',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('intervalo_minutos', models.PositiveIntegerField(default=30, verbose_name='Intervalo entre atendimentos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('duracao_minutos', models.PositiveIntegerField(verbose_name='Duração (minutos)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='servicos/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('cliente_telefone', models.CharField(max_length=16, verbose_name='Telefone (WhatsApp)')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20, verbose_name='Status')),
                ('nota_avaliacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota (1-5)')),
                ('comentario_avaliacao', models.TextField(blank=True, null=True, verbose_name='Comentário da Avaliação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='cadastros.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data', 'horario'],
            },
        ),
    ]
